// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svykiymlebdgraumbjbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2eWtpeW1sZWJkZ3JhdW1iamJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4NTU2MzgsImV4cCI6MjA1MTQzMTYzOH0.8cDxjekldqzYXvIyyNqWszfg06TlvgOMWp2QVgTfmLg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);